# Generated by Django 6.1 on 2026-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_companyprofile_candidateprofile_desired_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
